XlibInt.h: prevent Win32 CreateWindow macro from leaking into our code
Prevents compiler errors such as:

../../include/X11/Xlibint.h:542:16: error: 'xCreateWindowAReq' undeclared
 (first use in this function); did you mean 'xCreateWindowReq'?
  542 |         req = (x##name##Req *) _XGetRequest(dpy, X_##name, sz)
      |                ^
../../include/X11/Xlibint.h:554:9: note: in expansion of macro 'GetReqSized'
  554 |         GetReqSized(name, SIZEOF(x##name##Req), req)
      |         ^~~~~~~~~~~
cmsCmap.c:159:17: note: in expansion of macro 'GetReq'
  159 |                 GetReq(CreateWindow, req);
      |                 ^~~~~~

Fixes: eb1c272a ("Fix a9e845 and 797755 Allow X*IfEvent() to reenter libX11")
Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>
Part-of: <https://gitlab.freedesktop.org/xorg/lib/libx11/-/merge_requests/299>